local=true

[ansi]
dialect = "mysql"
driver = "pymysql"
dbname= 'planet_persib'
port= '3306'
password= 'Fh75io5SzY21'
schema= 'planetps'
hostname= 'ansi-production.ccjbghdpxc7u.ap-southeast-1.rds.amazonaws.com'
username= 'admin'

[installment]
dialect = "postgresql"
hostname= 'pp-production.ccjbghdpxc7u.ap-southeast-1.rds.amazonaws.com'
username= 'ppnftproduser'
password= 'rfCGJA6KMqjSFanwcg25EpvZhks3RNtU'
dbname= 'pp_installment_db_prod'
port='5432'

[tunnel]
username='ubuntu'
hostname='ec2-54-255-137-126.ap-southeast-1.compute.amazonaws.com'
pkey='william-pp'