[connections.postgresql]
dialect = "mysql"
driver = "pymysql"
host = "ansi.cutcvz7bts7s.ap-southeast-3.rds.amazonaws.com"
port = "3306"
database = "planet_persib"
username = "admin"
password = "Fh75io5SzY21"